version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio_c
    user: 1000:1000
    environment:
      MINIO_ROOT_USER: rupesh
      MINIO_ROOT_PASSWORD: xxxxxx
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    restart: always
    command: server /data --console-address ":9001"

volumes:
  minio_data:
    driver: local
